# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks

ci:
    autoupdate_schedule: monthly

repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.4.0
    hooks:
    -   id: trailing-whitespace
    -   id: end-of-file-fixer
    -   id: check-docstring-first
    -   id: check-json
    -   id: check-toml
    -   id: pretty-format-json
        exclude: \.ipynb
    -   id: mixed-line-ending
    -   id: check-yaml
        args: ["--unsafe"]
    -   id: check-added-large-files
        args: ["--maxkb=750"]
-   repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
    - id: black-jupyter

-   repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
    - id: isort
      name: isort (python)
      args: ["--profile", "black"]
    - id: isort
      name: isort (cython)
      types: [cython]
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    - id: flake8
      additional_dependencies: [
        flake8-bugbear==22.7.1,
        flake8-logging-format==0.7.4,
        flake8-2020==1.6.1,
      ]
- repo: https://github.com/sphinx-contrib/sphinx-lint
  rev: v0.8.1
  hooks:
    - id: sphinx-lint
- repo: https://github.com/pre-commit/pygrep-hooks
  rev: v1.10.0
  hooks:
    - id: rst-backticks
    - id: rst-directive-colons
    - id: rst-inline-touching-normal
    - id: text-unicode-replacement-char
- repo: https://github.com/PyCQA/pydocstyle
  rev: 6.3.0
  hooks:
    - id: pydocstyle
      files: ^((?!tests).)*[^(setup)]\.py
- repo: https://github.com/executablebooks/mdformat
  rev: 0.7.17
  hooks:
    - id: mdformat
-   repo: https://github.com/codespell-project/codespell
    rev: v2.2.6
    hooks:
    -   id: codespell
        args: ["-L ded"]
        exclude: \.ipynb
