#======================================================================================================================#
#                                       Cluster Generator Configuration File                                           #
#                                     +--------------------------------------+                                         #
#                                                                                                                      #
# This file contains the basic configuration settings for cluster_generator. See the line comments for details on      #
#   specific settings. Users are encouraged to edit settings and / or change settings as necessary.                    #
#                                                                                                                      #
# --- These settings are accessed using the cg.cgparams variable ------------------------------------------------------#
#======================================================================================================================#
system:
  # -- These are system-wide settings for basic usage. -- #
  preferences:
    # General user preferences
    disable_progress_bars: false    # Change to true to disable all progress bars in the module.
logging:
  # -- Settings pertaining to the logging system in pyXMIP -- #
  # There are 2 loggers in the cluster_generator module: mainlog and devlog.
  mylog:
    # Settings for the mainlog. This is the log which displays to stdout for most processes.
    format: '%(name)-3s : [%(levelname)-9s] %(asctime)s %(message)s' # Logger's string format for output
    level: INFO      # Only logging passed to this level or higher are displayed.
    stream: stderr   # Can be STDERR or STDOUT.
  devlog:
    # The developer log. This will increase the ammount of technical detail printed to stdout.
    enabled: false
    format: '%(name)-3s : [%(levelname)-9s] %(asctime)s %(message)s' # Logger's string format for output
    level: DEBUG    # Only logging passed to this level or higher are displayed.
    stream: stderr   # Can be STDERR or STDOUT.


#======================================================================================================================#
physics:
  # -- The physics settings are basic user-configurable physical parameters -- #
  hydrogen_abundance: 0.76 # The primordial hydrogen abundance (0.76 generally accepted value)

#======================================================================================================================#
plotting:
  # These are options for any of the default plots generated in cluster generator.
  defaults:
    # -- Latex settings -- #
    text.usetex: false
    # -- Tick Settings -- #
    xtick.major.size: 8
    ytick.major.size: 8
    xtick.minor.size: 5
    ytick.minor.size: 5
    xtick.direction: "in"
    ytick.direction: "in"
